# Generated by Django 3.1 on 2020-09-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogPost',
            new_name='Post',
        ),
    ]
